const quotes = [
  "Your smile",
  "Your eyes",
  "The way you look at me",
  "The way you calm my storms",
  "Your patience",
  "Your kindness",
  "Your voice",
  "The way you say my name",
  "How you care",
  "How you spoil me",
  "Your silence",
  "Your touch",
  "Your hugs",
  "The way you listen",
  "How you see through me",
  "Your little surprises",
  "Your big heart",
  "The way you believe in me",
  "Your laugh",
  "The way you cry",
  "Your soul",
  "The way you fight for us",
  "Your late-night talks",
  "The way you apologize",
  "How you make things better",
  "The way you forgive",
  "How you understand",
  "Your warmth",
  "Your flaws",
  "The way you remember details",
  "Your random texts",
  "How you hold my hand",
  "The way you miss me",
  "Your protectiveness",
  "Your dreams",
  "Your fear of losing me",
  "Your voice notes",
  "The way you make me laugh",
  "The way you look sleepy",
  "Your crazy ideas",
  "How you comfort me",
  "The way you respect me",
  "The way you look in my eyes",
  "Your little jealous moments",
  "Your shyness",
  "Your strength",
  "Your soft heart",
  "How you value small things",
  "How you say \"I'm here\"",
  "How you wait",
  "How you explain calmly",
  "The way you say \"I love you\"",
  "How you fight fair",
  "The way you get emotional",
  "The way you love music",
  "Your loyalty",
  "Your insecurities",
  "Your growth",
  "Your attention to me",
  "Your stubbornness",
  "Your hands",
  "Your heartbeats",
  "How you let me be me",
  "How you accept my darkness",
  "The way you inspire me",
  "The way you kiss",
  "How you look when you're mad",
  "How you fix broken things",
  "How you tease me",
  "The way you laugh at my jokes",
  "The way you heal me",
  "How you love me despite everything",
  "Your inner child",
  "Your courage",
  "The way you pull me closer",
  "The way you whisper",
  "The way you react to compliments",
  "The way you express love",
  "The way you talk about your day",
  "The way you sit in silence with me",
  "The way you get excited",
  "The way you trust me",
  "How you've changed me",
  "The way you know what I'm not saying",
  "Your sleepy voice",
  "The way you say goodnight",
  "The way you touch my soul",
  "The way you calm my anxiety",
  "The way you remind me of home",
  "The way you give me peace",
  "The way you still choose me",
  "The way you look at stars",
  "The way you laugh with your eyes",
  "The way you ask if I've eaten",
  "The way you remember my pain",
  "The way you call me yours",
  "How you stay in my mind",
  "The way you love me even when I'm unlovable",
  "Because you're you - and that's enough",
  "The way you gently wake me up",
  "Your dance moves",
  "How you love animals",
  "The way you light up when you talk about your passions",
  "How you look in my hoodie",
  "Your little rituals",
  "How you cry at movies",
  "Your morning face",
  "How you check in on me",
  "Your creativity",
  "Your thoughtful gifts",
  "The way you focus when you're thinking",
  "How you make any place feel like home",
  "Your ability to see beauty in little things",
  "The way you write",
  "How you make holidays special",
  "Your scent",
  "The way you say my name differently when you're happy",
  "How you celebrate my wins",
  "How you support my goals",
  "Your honesty",
  "How you challenge me to be better",
  "How you get excited about food",
  "Your little inside jokes",
  "The way you mock me",
  "Your sleepy texts",
  "How you give your all",
  "The way you react to surprises",
  "How you light up my darkest days",
  "How you're my peace and my fire",
  "The way you care for others",
  "How you sing in the shower",
  "How your happiness becomes mine",
  "The way you squint when you're curious",
  "How you always try",
  "How your energy fills the room",
  "Your silent strength",
  "The way you get nervous about my Instagram algorithm",
  "How you make life an adventure",
  "How you grow through pain",
  "Your sarcasm",
  "Your ambition",
  "How you're both strong and soft",
  "Your silly snaps",
  "How you make waiting worth it",
  "Your faith",
  "How you always try to fix things",
  "The way you twirl your hair",
  "Your love for sunsets",
  "Your ability to read the room",
  "Your eye rolls",
  "How you remember my stories",
  "The way you look in the rearview mirror",
  "The way you brush your hair back",
  "How you hum when you're focused",
  "Your clumsiness",
  "Your wild dreams",
  "The way you believe in second chances",
  "How you never give up on us",
  "My favorite boxer that you stole",
  "How you glow when you’re passionate",
  "How you let me be silly",
  "The way you lean on me",
  "How you always find the right words",
  "Your sweet notes",
  "How you hold me tighter on bad days",
  "The way you sip coffee",
  "Your excitement for little plans",
  "How you love your family",
  "The way you bounce back",
  "How you speak your truth",
  "Your voice when you’re half asleep",
  "Your fire when you're passionate",
  "Your random facts",
  "How you try to understand me",
  "The way you trust the process",
  "Your scent on my clothes",
  "The way you hold in tears",
  "The way you count stars",
  "Your ability to forgive",
  "How you fight for what you love",
  "The way you say \"we got this\"",
  "How you take care of me when I'm sick",
  "Your fascination with little things",
  "How your presence makes me feel safe",
  "The way you paint your nails and smudge one",
  "Your late-night rambles",
  "How you always come back",
  "Your belief in us",
  "Your love for books",
  "How you cheer for me even in silence",
  "How you look when you're thinking",
  "Your selfies",
  "The way you laugh with your whole body",
  "How you remember what I love",
  "The way you make future plans",
  "Your stubborn love",
  "The way you say “I miss you”",
  "Your comfort in chaos",
  "How you grow even when it's hard",
  "Your sleepy giggles",
  "The way you smell my clothes",
  "How you dance in the rain",
  "How you love without limits",
  "The way you fix my hair",
  "How you laugh when you're nervous",
  "Your love for nostalgia",
  "Your random \"just because\" gifts",
  "Your calming presence",
  "How you overthink because you care",
  "How you stay soft in a harsh world",
  "The way you hold my face",
  "How you light up when you see me",
  "Your playlist",
  "The way you walk beside me",
  "Your curiosity",
  "How you never let go of hope",
  "The way you play with my hair",
  "How you always try to see the good",
  "The way you say “ours”",
  "Your late-night “thinking face”",
  "How you whisper my name",
  "Your choice to stay",
  "The way you love your favorite things",
  "How you find beauty in yourself",
  "Your secret glances",
  "Your love for the nature",
  "The way you light candles",
  "The way you stretch when you wake up",
  "Your clingy moments",
  "Your proud smile",
  "The way you hold our memories",
  "Your silly faces",
  "The way you say “Tarek”",
  "How you match your outfits",
  "The way you laugh when you’re embarrassed",
  "Your soft “hi”",
  "Your need to protect what you love",
  "The way you pout",
  "Your unmatched energy",
  "The way you talk to animals",
  "Your spontaneous hugs",
  "How you trust me with your truths",
  "The way you scribble",
  "Your signature look",
  "How you hold my secrets",
  "The way you say “I’m listening”",
  "How you open up little by little",
  "Your sweet morning messages",
  "The way you say “I’m proud of you”",
  "Your way of grounding me",
  "How you remember my routines",
  "How your hands find mine",
  "The way you adjust my clothes",
  "Your unconditional love",
  "Your sense of fairness",
  "How you get lost in your thoughts",
  "How your heart chooses me",
  "The way you hold your tears",
  "The way you share your silence",
  "How you feel like destiny",
  "Your dreams that include me",
  "The way you bloom in love",
  "The way you’ve become my favorite person"
];
